background {
    monitor =
    path = screenshot
    blur_passes = 2
}
input-field {
  monitor =
  size = 250, 60
  halign = center
  valign = center
  position = 0, -50
  fade_on_empty = false
  outline_thickness = 4
  outer_color = rgb(250, 179, 135)
  inner_color = rgb(30, 30, 46)
  dots_center = true
  placeholder_text = <span>Enter Password...</span>
  font_color = rgb(205, 214, 244)
  font_family = JetBrains Mono Nerd Font
  fail_color = rgb(243, 139, 168)
  fail_text = <i>Incorrect Password($ATTEMPTS)</i>
}
label {
  monitor =
  text = $TIME
  halign = center
  valign = center
  position = 0, 150
  font_size = 90
  font_family = JetBrains Mono Nerd Font
  color = rgb(205, 214, 244)
}
label {
  monitor =
  text = cmd[update:1000] echo "$(date +"%A, %d %B")"
  halign = center
  valign = center
  position = 0, 70
  font_size = 22
  font_family = JetBrains Mono Nerd Font
  color = rgb(147, 153, 178)
}
